package:
  name: "meteovis"
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/jiqicn/meteovis

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - ipywidgets
    - ipyfilechooser
    - ipyleaflet
    - qgrid
    - pandas
    - h5py
    - numpy
    - wradlib

about:
  home: https://github.com/jiqicn/meteovis
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "A jupyter-based tool for visualizing and exploring meteorological and bioecological data hosted at UvA-TCE."

extra:
  recipe-maintainers:
    - jiqicn